### ISSUE TITLE
Morning session code review Thursday

### ISSUE THREAD

**Issue by Yordinia** [0sugo/to-do-list#4]
In this project we have found the following issues

- [ ]   Unnesessary unnecessary import and use of code in index.js file

![image](https://user-images.githubusercontent.com/75666332/229289174-5c5a63a4-e1ac-4ac6-a0c8-cda847508283.png)
- [ ] It would be appropriate to remove comments from your code.

Thank you.

**Comment by 0sugo** [comment]
Thanks for the correction

**Comment by Yordinia** [comment]
your welcome 🙏
